-- DROP USER PAGARME;

CREATE USER PAGARME
-- IDENTIFIED BY <password>
;

CREATE TABLE "PAGARME"."ADDRESS" 
   (	"ADDRESS_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"CITY" VARCHAR2(255), 
	"COUNTRY" VARCHAR2(255), 
	"CREATED_AT" DATE, 
	"LINE_1" VARCHAR2(255), 
	"LINE_2" VARCHAR2(255), 
	"STATE" VARCHAR2(255), 
	"STATUS" VARCHAR2(255), 
	"UPDATED_AT" DATE, 
	"ZIP_CODE" VARCHAR2(255), 
	 PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008523" ON "PAGARME"."ADDRESS" ("ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."CARD" 
   (	"CARD_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"CARD_BRAND" VARCHAR2(255), 
	"FIRST_SIX_DIGITS" VARCHAR2(255), 
	"HOLDER_NAME" VARCHAR2(255), 
	"LAST_FOUR_DIGITS" VARCHAR2(255), 
	 PRIMARY KEY ("CARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PAGARME" ;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008525" ON "PAGARME"."CARD" ("CARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."CHARGE" 
   (	"CHARGE_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"AMOUNT" FLOAT(126), 
	"CODE" VARCHAR2(255), 
	"CREATED_AT" DATE, 
	"CURRENCY" VARCHAR2(255), 
	"GATEWAY_ID" VARCHAR2(255), 
	"PAID_AMOUNT" FLOAT(126), 
	"PAID_AT" DATE, 
	"PAYMENT_METHOD" VARCHAR2(255), 
	"STATUS" VARCHAR2(255), 
	"UPDATED_AT" DATE, 
	"CUSTOMER_ID" VARCHAR2(255), 
	"LAST_TRANSACTION_ID" VARCHAR2(255), 
	"ORDER_ID" VARCHAR2(255), 
	 PRIMARY KEY ("CHARGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PAGARME" ;

ALTER TABLE "PAGARME"."CHARGE" ADD CONSTRAINT "FK_7E727ADVXYUCPYSJ5DF9NMPKC" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "PAGARME"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "PAGARME"."CHARGE" ADD CONSTRAINT "FK_DR87X62BDPUQHIRO0KTE9XJS7" FOREIGN KEY ("LAST_TRANSACTION_ID")
	  REFERENCES "PAGARME"."LAST_TRANSACTION" ("LAST_TRANSACTION_ID") ENABLE;
  ALTER TABLE "PAGARME"."CHARGE" ADD CONSTRAINT "FK_BD7P1YO681L2HTQJF91KPBKHH" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "PAGARME"."ORDERS" ("ORDER_ID") ENABLE;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008527" ON "PAGARME"."CHARGE" ("CHARGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."CHECKOUT" 
   (	"CHECKOUT_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"ORDER_ID" VARCHAR2(255), 
	 PRIMARY KEY ("CHECKOUT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PAGARME" ;

ALTER TABLE "PAGARME"."CHECKOUT" ADD CONSTRAINT "FK_9G39NGOGUGR6D3RCO4R9OGPC1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "PAGARME"."ORDERS" ("ORDER_ID") ENABLE;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008529" ON "PAGARME"."CHECKOUT" ("CHECKOUT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."CUSTOMER" 
   (	"CUSTOMER_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"BIRTHDATE" DATE, 
	"CODE" VARCHAR2(255), 
	"CREATED_AT" DATE, 
	"DELINQUENT" NUMBER(1,0), 
	"DOCUMENT" VARCHAR2(255), 
	"DOCUMENT_TYPE" VARCHAR2(255), 
	"EMAIL" VARCHAR2(255), 
	"GENDER" VARCHAR2(255), 
	"NAME" VARCHAR2(255), 
	"TYPE" VARCHAR2(255), 
	"UPDATED_AT" DATE, 
	"ADDRESS_ID" VARCHAR2(255), 
	"PHONES_ID" NUMBER(19,0), 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;

ALTER TABLE "PAGARME"."CUSTOMER" ADD CONSTRAINT "FK_R8WHBD0MF9ER6VWFR0SCLSXKD" FOREIGN KEY ("ADDRESS_ID")
	  REFERENCES "PAGARME"."ADDRESS" ("ADDRESS_ID") ENABLE;
  ALTER TABLE "PAGARME"."CUSTOMER" ADD CONSTRAINT "FK_IJS939NXQ75YL8K9IDA5J19X" FOREIGN KEY ("PHONES_ID")
	  REFERENCES "PAGARME"."PHONES" ("PHONES_ID") ENABLE;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008531" ON "PAGARME"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."HOME_PHONE" 
   (	"HOME_PHONE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"AREA_CODE" VARCHAR2(255), 
	"COUNTRY_CODE" VARCHAR2(255), 
	"PHONE_NUMBER" VARCHAR2(255), 
	 PRIMARY KEY ("HOME_PHONE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008533" ON "PAGARME"."HOME_PHONE" ("HOME_PHONE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."ITEM" 
   (	"ITEM_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"AMOUNT" FLOAT(126), 
	"CODE" VARCHAR2(255), 
	"CREATED_AT" DATE, 
	"DESCRIPTION" VARCHAR2(255), 
	"QUANTITY" NUMBER(10,0), 
	"STATUS" VARCHAR2(255), 
	"TYPE" VARCHAR2(255), 
	"UPDATED_AT" DATE, 
	"ORDER_ID" VARCHAR2(255), 
	 PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PAGARME" ;

ALTER TABLE "PAGARME"."ITEM" ADD CONSTRAINT "FK_6RVOJ2S9KX8658ULXDBGWBMPV" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "PAGARME"."ORDERS" ("ORDER_ID") ENABLE;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008535" ON "PAGARME"."ITEM" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."LAST_TRANSACTION" 
   (	"LAST_TRANSACTION_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"ACQUIRER_AUTH_CODE" VARCHAR2(255), 
	"ACQUIRER_MESSAGE" VARCHAR2(255), 
	"ACQUIRER_NAME" VARCHAR2(255), 
	"ACQUIRER_NSU" VARCHAR2(255), 
	"ACQUIRER_RETURN_CODE" VARCHAR2(255), 
	"ACQUIRER_TID" VARCHAR2(255), 
	"AMOUNT" FLOAT(126), 
	"CREATED_AT" DATE, 
	"FUNDING_SOURCE" VARCHAR2(255), 
	"GATEWAY_ID" VARCHAR2(255), 
	"INSTALLMENTS" NUMBER(10,0), 
	"OPERATION_TYPE" VARCHAR2(255), 
	"STATEMENT_DESCRIPTOR" VARCHAR2(255), 
	"STATUS" VARCHAR2(255), 
	"SUCCESS" NUMBER(1,0), 
	"TRANSACTION_TYPE" VARCHAR2(255), 
	"UPDATED_AT" DATE, 
	"CARD_ID" VARCHAR2(255), 
	"CHARGE_ID" VARCHAR2(255), 
	 PRIMARY KEY ("LAST_TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PAGARME" ;

ALTER TABLE "PAGARME"."LAST_TRANSACTION" ADD CONSTRAINT "FK_IJ20K19VYOVX28A314NN20RL6" FOREIGN KEY ("CARD_ID")
	  REFERENCES "PAGARME"."CARD" ("CARD_ID") ENABLE;
  ALTER TABLE "PAGARME"."LAST_TRANSACTION" ADD CONSTRAINT "FK_KHAN856SHJ1J9GYTSM1I3819M" FOREIGN KEY ("CHARGE_ID")
	  REFERENCES "PAGARME"."CHARGE" ("CHARGE_ID") ENABLE;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008537" ON "PAGARME"."LAST_TRANSACTION" ("LAST_TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."MOBILE_PHONE" 
   (	"MOBILE_PHONE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"AREA_CODE" VARCHAR2(255), 
	"COUNTRY_CODE" VARCHAR2(255), 
	"PHONE_NUMBER" VARCHAR2(255), 
	 PRIMARY KEY ("MOBILE_PHONE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008539" ON "PAGARME"."MOBILE_PHONE" ("MOBILE_PHONE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."ORDERS" 
   (	"ORDER_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"AMOUNT" FLOAT(126), 
	"CLOSED" NUMBER(1,0), 
	"CLOSED_AT" DATE, 
	"CODE" VARCHAR2(255), 
	"CREATED_AT" DATE, 
	"CURRENCY" VARCHAR2(255), 
	"STATUS" VARCHAR2(255), 
	"UPDATED_AT" DATE, 
	"CUSTOMER_ID" VARCHAR2(255), 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PAGARME" ;

ALTER TABLE "PAGARME"."ORDERS" ADD CONSTRAINT "FK_ASTYS1DV61MDLP0N0WX0574R2" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "PAGARME"."CUSTOMER" ("CUSTOMER_ID") ENABLE;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008541" ON "PAGARME"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "PAGARME" ;
;

CREATE TABLE "PAGARME"."PHONES" 
   (	"PHONES_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"HOME_PHONE_ID" NUMBER(19,0), 
	"MOBILE_PHONE_ID" NUMBER(19,0), 
	 PRIMARY KEY ("PHONES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;

ALTER TABLE "PAGARME"."PHONES" ADD CONSTRAINT "FK_2S8LKLLK4KHB7RCB8P6SV5B2P" FOREIGN KEY ("HOME_PHONE_ID")
	  REFERENCES "PAGARME"."HOME_PHONE" ("HOME_PHONE_ID") ENABLE;
  ALTER TABLE "PAGARME"."PHONES" ADD CONSTRAINT "FK_G0Q2KW9AX7F4XW905M5SRYTUL" FOREIGN KEY ("MOBILE_PHONE_ID")
	  REFERENCES "PAGARME"."MOBILE_PHONE" ("MOBILE_PHONE_ID") ENABLE;

CREATE UNIQUE INDEX "PAGARME"."SYS_C008543" ON "PAGARME"."PHONES" ("PHONES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PAGARME" ;
;

CREATE SEQUENCE PAGARME.SEQ_HOME_PHONE_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PAGARME.SEQ_MOBILE_PHONE_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PAGARME.SEQ_PHONES_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

